In [1]:
# Importation des librairies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Importation du dataset
df = pd.read_csv("../data/processed_dataset.csv")
df.head()

,Chambres,Salon,SalleDeBainInterieure,Parking,Meuble,Jardin,Superficie_m2,DistanceRoute_m,Quartier,AgeMaison,LoyerMensuel_BIF
0,4.0,Oui,Oui,NaN,Non,Oui,192.0,277.0,Rohero,17.0,2600000
1,5.0,Oui,Oui,Non,Oui,Non,234.0,47.0,Rohero,37.0,2600000
2,3.0,Oui,Oui,Non,Non,Oui,151.0,45.0,Kinanira,23.0,1069218
3,5.0,Oui,Oui,Oui,Oui,Oui,227.0,174.0,Gasekebuye,22.0,2600000
4,5.0,Oui,Oui,Oui,NaN,Non,262.0,216.0,Gihosha,21.0,2085458

# Créer *Confort_Score*, puis supprimer les 5 colonnes individuelles.

Le calcul de **Confort_Score** ne doit pas être réalisé directement sur des variables contenant des valeurs manquantes, car cela produirait un score partiellement biaisé. Les variables binaires doivent d’abord être encodées puis imputées avant la création de cette variable composite, afin de garantir une interprétation cohérente du niveau de confort du logement.

In [3]:
# Créer une variable Confort_Score correspondant à la somme des 5 variables binaires
binary_cols = ["Salon", "SalleDeBainInterieure", "Parking", "Meuble", "Jardin"]

# Remplacement des textes avec valeurs
for col in binary_cols:
    df[col] = df[col].map({"Oui": 1, "Non": 0})

# Imputation avant score
for col in binary_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df["Confort_Score"] = df[binary_cols].sum(axis=1)
#df['Confort_Score'] = df['Salon'] + df['SalleDeBainInterieure'] + df['Parking'] + df['Meuble'] + df['Jardin']

In [4]:
# Supprimer ensuite les 5 colonnes individuelles
df = df.drop(columns=["Salon", "SalleDeBainInterieure", "Parking", "Meuble", "Jardin"], axis=1)
df.head()

,Chambres,Superficie_m2,DistanceRoute_m,Quartier,AgeMaison,LoyerMensuel_BIF,Confort_Score
0,4.0,192.0,277.0,Rohero,17.0,2600000,4.0
1,5.0,234.0,47.0,Rohero,37.0,2600000,3.0
2,3.0,151.0,45.0,Kinanira,23.0,1069218,3.0
3,5.0,227.0,174.0,Gasekebuye,22.0,2600000,5.0
4,5.0,262.0,216.0,Gihosha,21.0,2085458,3.0

# Création de *Chambres_par_Superficie*

In [5]:
# Création de la feature de densité (AVANT de supprimer la colonne Chambres)
df['Chambres_par_Superficie'] = df['Chambres'] / df['Superficie_m2']

In [6]:
df.to_csv("../data/train_data.csv", index=False)
df

,Chambres,Superficie_m2,DistanceRoute_m,Quartier,AgeMaison,LoyerMensuel_BIF,Confort_Score,Chambres_par_Superficie
0,4.0,192.0,277.0,Rohero,17.0,2600000,4.0,0.020833
1,5.0,234.0,47.0,Rohero,37.0,2600000,3.0,0.021368
2,3.0,151.0,45.0,Kinanira,23.0,1069218,3.0,0.019868
3,5.0,227.0,174.0,Gasekebuye,22.0,2600000,5.0,0.022026
4,5.0,262.0,216.0,Gihosha,21.0,2085458,3.0,0.019084
...,...,...,...,...,...,...,...,...
505,5.0,NaN,65.0,Kamenge,15.0,1160062,4.0,NaN
506,5.0,241.0,205.0,Ngagara,4.0,1675700,3.0,0.020747
507,4.0,192.0,277.0,Rohero,17.0,2600000,4.0,0.020833
508,6.0,276.0,NaN,Kinanira,38.0,1831063,2.0,0.021739
509,5.0,241.0,213.0,Gasekebuye,3.0,2504289,3.0,0.020747